spring.application.name=telecom-assistant

server.servlet.context-path = /telecom-assistant

spring.datasource.url = jdbc:postgresql://localhost:5432/postgres?currentSchema=telecomassist
spring.datasource.username = ${POSTGRES_USER}
spring.datasource.password = ${POSTGRES_PASSWORD}

spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration/

spring.ai.openai.chat.options.model = gpt-5
spring.ai.openai.api-key = ${OPEN_AI_J_API_KEY}
spring.ai.openai.chat.options.temperature = 1

#TODO 1: enable MCP client and configure the MCP servers
#spring.ai.mcp.client.name = telecom-mcp-client
#spring.ai.mcp.client.version = 1.0.0
#spring.ai.mcp.client.request-timeout = 30s
#spring.ai.mcp.client.toolcallback.enabled = true

#spring.ai.mcp.client.streamable-http.connections.invoice.url = http://localhost:8081
#spring.ai.mcp.client.streamable-http.connections.invoice.endpoint = /mcp-invoice

#spring.ai.mcp.client.streamable-http.connections.vendor.url = http://localhost:8082
#spring.ai.mcp.client.streamable-http.connections.vendor.endpoint = /mcp-vendor

management.endpoints.web.exposure.include = health,info,flyway
