spring.application.name=telecom-assistant

server.servlet.context-path = /telecom-assistant

spring.ai.openai.chat.options.model = gpt-5
spring.ai.openai.api-key = ${OPEN_AI_J_API_KEY}
spring.ai.openai.chat.options.temperature = 1
