spring.application.name=invoice-mcp-server

server.port = 8081

spring.datasource.url = jdbc:postgresql://localhost:5432/postgres?currentSchema=telecomassist
spring.datasource.username = ${POSTGRES_USER}
spring.datasource.password = ${POSTGRES_PASSWORD}

spring.ai.mcp.server.name = telecom-invoice-mcp-server
spring.ai.mcp.server.version = 1.0.0
spring.ai.mcp.server.instructions = Instructions - endpoint: /mcp, type: sync, protocol: streamable

spring.ai.mcp.server.type = sync
spring.ai.mcp.server.protocol = streamable

spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp

spring.ai.mcp.server.capabilities.tool = true
spring.ai.mcp.server.capabilities.completion = false
spring.ai.mcp.server.capabilities.prompt = false
spring.ai.mcp.server.capabilities.resource = false

# id is the tenant using the server
# each tenant has its own api key id and secret
# the header is the same for all tenants using this server - invoice-x-api-key
api.key.id=${API_KEY_ID}
api.key.secret=${API_KEY_SECRET}

