spring.application.name = invoice-mcp-server

server.port = 8081

spring.datasource.url = jdbc:postgresql://localhost:5432/postgres?currentSchema=telecomassist
spring.datasource.username = ${POSTGRES_USER}
spring.datasource.password = ${POSTGRES_PASSWORD}

spring.ai.mcp.server.name = telecom-invoice-mcp-server
spring.ai.mcp.server.version = 1.0.0
spring.ai.mcp.server.instructions = Instructions - endpoint: /mcp-invoice, type: sync, protocol: streamable

spring.ai.mcp.server.type = sync
spring.ai.mcp.server.protocol = streamable

spring.ai.mcp.server.streamable-http.mcp-endpoint = /mcp-invoice

spring.ai.mcp.server.capabilities.tool = true
spring.ai.mcp.server.capabilities.completion = false
spring.ai.mcp.server.capabilities.prompt = false
spring.ai.mcp.server.capabilities.resource = false
