DROP TABLE IF EXISTS Vendors CASCADE;
CREATE TABLE IF NOT EXISTS Vendors (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR NOT NULL UNIQUE
);

DROP TABLE IF EXISTS ServiceTypes CASCADE;
CREATE TABLE IF NOT EXISTS ServiceTypes (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR NOT NULL UNIQUE
);

DROP TABLE IF EXISTS Invoices CASCADE;
CREATE TABLE IF NOT EXISTS Invoices (
    Id SERIAL PRIMARY KEY,
    Number VARCHAR NOT NULL UNIQUE,
    Date DATE NOT NULL,
    VendorId INTEGER NOT NULL,
    ServiceTypeId INTEGER NOT NULL,
    Status VARCHAR NOT NULL,
    Total NUMERIC(18, 2) DEFAULT 0.0 NOT NULL,
    CONSTRAINT FK_Invoices_ServiceTypes FOREIGN KEY (ServiceTypeId) REFERENCES ServiceTypes(Id),
    CONSTRAINT FK_Invoices_Vendors FOREIGN KEY (VendorId) REFERENCES Vendors(Id)
);

ALTER TABLE Invoices DROP CONSTRAINT IF EXISTS CHK_Invoices_Status;
ALTER TABLE Invoices
    ADD CONSTRAINT CHK_Invoices_Status CHECK (Status IN ('UNDER_REVIEW', 'APPROVED', 'PAID'));
